# Generated by Django 2.0.6 on 2019-03-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='image',
            field=models.CharField(default='', max_length=900),
        ),
    ]
